name: Bug Report
description: Report a bug
title: '[Bug] '
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in improving the project! Before submitting, please read our guidelines.
        感谢您对改进项目的兴趣！提交前请阅读我们的指南。

        - [Code of Conduct](https://github.com/alibaba/page-agent/blob/main/CODE_OF_CONDUCT.md)
        - [Contributing Guide](https://github.com/alibaba/page-agent/blob/main/CONTRIBUTING.md)

  - type: textarea
    id: description
    attributes:
      label: What happened?
      placeholder: Describe the bug and expected behavior
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Code
      render: typescript
      placeholder: Minimal reproduction code
    validations:
      required: false

  - type: input
    id: browser
    attributes:
      label: Browser
      placeholder: 'Chrome 120, Firefox 119, etc.'
    validations:
      required: false

  - type: input
    id: version
    attributes:
      label: version
      placeholder: '0.0.0'
    validations:
      required: false

  - type: checkboxes
    id: community
    attributes:
      label: Community Communication / 社区沟通
      description: Confirm you will communicate respectfully and constructively / 确认将以礼貌、建设性的方式沟通
      options:
        - label: I will be polite and respectful. / 我会保持礼貌与尊重。
          required: true
        - label: I will share constructive, actionable suggestions. / 我会提供建设性、可行动的建议。
          required: true
        - label: I have read the Code of Conduct. / 我已阅读行为准则。
          required: true
    validations:
      required: true