name: Feature Request
description: Suggest a feature
title: '[Feature] '
labels: ['enhancement']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in improving the project! Before submitting, please read our guidelines.
        感谢您对改进项目的兴趣！提交前请阅读我们的指南。

        - [Code of Conduct](https://github.com/alibaba/page-agent/blob/main/CODE_OF_CONDUCT.md)
        - [Contributing Guide](https://github.com/alibaba/page-agent/blob/main/CONTRIBUTING.md)

  - type: textarea
    id: description
    attributes:
      label: Feature Description / 功能描述
      description: Describe the problem, solution, and any API changes. / 描述问题、解决方案以及 API 变更。
      placeholder: |
        **Problem**:
        What problem does this solve?

        **Solution**:
        How should this work?

        **Proposed API**:
        ```typescript
        // code here
        ```
    validations:
      required: true

  - type: checkboxes
    id: community
    attributes:
      label: Community Communication / 社区沟通
      description: Confirm you will communicate respectfully and constructively / 确认将以礼貌、建设性的方式沟通
      options:
        - label: I will be polite and respectful. / 我会保持礼貌与尊重。
          required: true
        - label: I will share constructive, actionable suggestions. / 我会提供建设性、可行动的建议。
          required: true
        - label: I have read the CODE_OF_CONDUCT.md and CONTRIBUTING.md. / 我已阅读行为准则。
          required: true
    validations:
      required: true